name: deploy
on:
  workflow_run:
    workflows: ["build-test"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image Tag'
        required: false
        default: 'latest'
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, ARM64]
    env:
      IMAGE_NAME: node_express_api
      APP_SERVER_PORT: 3000
      COMMIT_SHA_TAG: ${{ github.sha }}
    steps:
        - run: |
            export EXISTING_CONTAINER_ID=$(sudo docker ps --quiet --filter name=$IMAGE_NAME)
            if [[ -z "${EXISTING_CONTAINER_ID-}" ]]; then echo "No existing container named $IMAGE_NAME is running. Exiting current step." && exit 0; fi
            sudo docker inspect $EXISTING_CONTAINER_ID --format 'ID {{ .Id }} {{printf "\n"}}Started at {{ .State.StartedAt }} {{printf "\n"}}Image ID {{ .Image }}'
            sudo docker rm --force $EXISTING_CONTAINER_ID
        - run: sudo docker run --name $IMAGE_NAME --detach --publish 80:$APP_SERVER_PORT $IMAGE_NAME:$COMMIT_SHA_TAG
